name: Build Jekyll site (No Deploy)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          rm -f Gemfile.lock
          bundle install

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --trace
        env:
          JEKYLL_ENV: production
