name: Manual Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write  # Needed to push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          rm -f Gemfile.lock
          bundle install

      - name: Build site with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy _site to gh-pages branch
        run: |
          cd _site
          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote add origin https://github.com/${{ github.repository }}.git
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy site"
          git push --force origin gh-pages
